let nombre = "Marina";
let edad = 46;
let estatura = 1.5;
let casado = true;
document.writeln(nombre);
document.write("<br>");
document.writeln(edad);
let profesion = prompt("Digita tu profesión");
alert("Tu profesión es " + profesion);
//let nom = document.getElementById("t1");
document.write(nom);
document.getElementById("t1").innerHTML = nombre;